"""
orchestrator/pdlc.py — M8: Two-Layer Repo Split (D33).

`emit_pdlc_artifacts(state, target_path)` writes Continuum's Layer 1 pipeline
outputs into the `.pdlc/` directory of a Layer 2 target application repo.

Layer 1 (Process): orchestrator/, agents/, skills/, evals/, UI — lives in the
Continuum repo and drives the SDLC; never modified by the pipeline itself.

Layer 2 (Product): the target application being developed. Continuum writes a
`.pdlc/` directory into it containing:

    .pdlc/
    ├── run_manifest.json   — run metadata, cost, status, mapping fidelity
    ├── evidence.json       — 6-layer Evidence Stack (merge-readiness proof)
    ├── contracts/
    │   ├── openapi.yaml    — OpenAPI contract generated by Architect
    │   └── schema.sql      — DB schema generated by Architect
    └── generated/
        └── <file_path>     — code produced by DATABASE/BACKEND/FRONTEND agents

Offline-safe: pure file I/O, no network, no credentials required.
"""
from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any, Dict

from evals.evidence_stack import build_evidence_stack

logger = logging.getLogger(__name__)


async def emit_pdlc_artifacts(state: Any, target_path: str) -> Dict[str, Any]:
    """
    Write pipeline artifacts to .pdlc/ in the target repo. Offline-safe.

    Side-effect: creates .pdlc/, .pdlc/contracts/, .pdlc/generated/ under
    target_path.  Always writes run_manifest.json and evidence.json even when
    the run produced no code (partial runs still need an audit trail).

    Returns:
        {"pdlc_path": str, "files_written": int, "files": list[str]}
    """
    pdlc = Path(target_path) / ".pdlc"
    pdlc.mkdir(parents=True, exist_ok=True)
    (pdlc / "generated").mkdir(exist_ok=True)
    (pdlc / "contracts").mkdir(exist_ok=True)

    files: list[str] = []

    # run_manifest.json — metadata + cost + scope-guard result
    manifest = {
        "run_id": getattr(state, "run_id", None) or "",
        "request": (getattr(state, "request", None) or "")[:200],
        "status": getattr(state, "run_status", "done"),
        "cost_usd": round(getattr(state, "cost_usd", 0.0), 4),
        "business_mappings": list(getattr(state, "business_mappings", []) or []),
        "mapping_fidelity": getattr(state, "mapping_fidelity", None),
        "reject_reason": getattr(state, "reject_reason", None),
    }
    _write(pdlc / "run_manifest.json", json.dumps(manifest, indent=2))
    files.append(".pdlc/run_manifest.json")

    # evidence.json — 6-layer merge-readiness proof (pure function of state)
    evidence = build_evidence_stack(state)
    _write(pdlc / "evidence.json", json.dumps(evidence, indent=2))
    files.append(".pdlc/evidence.json")

    # contracts/openapi.yaml
    contract = getattr(state, "contract", None)
    if contract:
        _write(pdlc / "contracts" / "openapi.yaml", contract)
        files.append(".pdlc/contracts/openapi.yaml")

    # contracts/schema.sql
    schema = getattr(state, "schema", None)
    if schema:
        _write(pdlc / "contracts" / "schema.sql", schema)
        files.append(".pdlc/contracts/schema.sql")

    # generated/<file_path> — code from developer agents
    for file_path, content in (getattr(state, "code", {}) or {}).items():
        dest = pdlc / "generated" / file_path
        dest.parent.mkdir(parents=True, exist_ok=True)
        _write(dest, content)
        files.append(f".pdlc/generated/{file_path}")

    result: Dict[str, Any] = {
        "pdlc_path": str(pdlc),
        "files_written": len(files),
        "files": files,
    }
    logger.info("M8 pdlc: %d files → %s", len(files), pdlc)
    return result


def _write(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")
