# File: continuum/orchestrator/state.py
# UPDATED: M3 — added episodic memory fields (episodes, episodes_written)
# UPDATED: M6 — added run_status, cost_usd, reject_reason (Work Queue + metrics)
# UPDATED: M7 — added business_mappings, mapping_fidelity (Scope-Guard)

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from enum import Enum

from orchestrator.state_machine import SDLCState


class AgentRole(str, Enum):
    ORCHESTRATOR = "orchestrator"
    BSA          = "bsa"
    ARCHITECT    = "architect"
    PLANNER      = "planner"
    DEVELOPER    = "developer"
    # M1: developer split into three specialised sub-agents (T3)
    DATABASE     = "database"   # runs first — migrations before API
    BACKEND      = "backend"    # REST API layer
    FRONTEND     = "frontend"   # SPA / UI layer (runs last)
    SECURITY     = "security"
    CODE_REVIEW  = "code_review"
    PR_REVIEW    = "pr_review"
    TEST         = "test"
    INFRA        = "infra"
    MEMORY       = "memory"
    EVOLUTION    = "evolution"


@dataclass
class AgentMessage:
    agent: AgentRole
    timestamp: float
    content: str
    tool_calls: List[Dict[str, Any]] = field(default_factory=list)
    tool_results: List[Dict[str, Any]] = field(default_factory=list)


@dataclass
class GateStatus:
    name: str    # "local_verify", "security_sast", "pr_review", "tests"
    status: str  # "green", "red", "pending"
    retry_count: int = 0
    error_message: Optional[str] = None
    last_checked: Optional[float] = None


@dataclass
class ContinuumState:
    # Input
    request: str

    # Orchestration
    current_agent: Optional[AgentRole] = None
    next_agent: Optional[AgentRole] = None

    # Control
    gates: List[GateStatus] = field(default_factory=list)
    messages: List[AgentMessage] = field(default_factory=list)

    # Rule 8: Plans are contracts (PEV loop)
    pev_contract: Optional[Dict[str, Any]] = None  # PEVContract.to_dict()

    # Artifacts
    story: Optional[Dict[str, Any]] = None   # {"id", "title", "acceptance_criteria", …}
    contract: Optional[str] = None           # OpenAPI YAML string
    schema: Optional[str] = None            # SQL DDL string
    dag: Optional[Dict[str, Any]] = None    # Neo4j DAG structure
    code: Optional[Dict[str, str]] = None   # {"file_path": content}
    test_results: Optional[Dict[str, Any]] = None
    pr_url: Optional[str] = None

    # State flags
    human_approval_pending: bool = False
    approval_gate_name: Optional[str] = None
    error_message: Optional[str] = None

    # M1: human approval checkpoints (interrupt() gates)
    story_approved:  bool = False   # True after human approves BSA story
    design_approved: bool = False   # True after human approves Architect design
    merge_approved:  bool = False   # True after human approves the final PR

    # M3: Episodic memory
    # Past episodes retrieved by graphrag_query at run start (grounding context).
    episodes: Optional[List[Dict[str, Any]]] = None
    # Episodes written by the Memory agent at run end.
    episodes_written: Optional[List[Dict[str, Any]]] = None

    # M5: Decomposition script generated by orchestrator/decomposer.py
    # Populated when state.dag has >= 5 tasks; stored for operator inspection.
    decomposition_script: Optional[str] = None

    # M6: Work Queue + run metrics
    # Lifecycle status surfaced to the Work Queue UI. Allowed values:
    #   running | waiting_gate | blocked | returned | done | failed
    # Set explicitly at pipeline transitions; _classify() prefers it over
    # the legacy derivation. Defaults to "running" so a fresh run is sane.
    run_status: str = "running"
    # Accumulated model cost in USD. Offline runs use a fixed per-agent estimate
    # (cost is always populated so the metric is never blank). Only ever added to.
    cost_usd: float = 0.0
    # Reason captured when a human rejects a story/design gate (run_status="returned").
    reject_reason: Optional[str] = None

    # M7: Mapping Fidelity (Scope-Guard, D11)
    # Business mappings supplied at intent time: [{code: "BR", label: "Branch"}, ...]
    business_mappings: List[Dict[str, Any]] = field(default_factory=list)
    # Populated by gate_scope_conformance after the developer chain runs.
    # Shape: {supplied, found, extra_in_code, missing_in_code, exact_match}
    mapping_fidelity: Optional[Dict[str, Any]] = None

    # M8: Two-Layer Repo Split (D33)
    # Absolute path of the .pdlc/ directory written into the target app repo.
    # Set after emit_pdlc_artifacts() runs; None if CONTINUUM_TARGET_REPO is unset.
    pdlc_path: Optional[str] = None

    # M11: Spec Registry
    # Deterministic component key this run's spec is filed under.
    component: Optional[str] = None
    # Version chain (oldest-first) the BSA retrieved from the Registry this run.
    registry_specs: List[Dict[str, Any]] = field(default_factory=list)
    # The prior current Registry spec for this component (None on a first run).
    registry_current_before: Optional[Dict[str, Any]] = None
    # {old_id, reason} when this run's spec superseded the prior one; else None.
    spec_superseded: Optional[Dict[str, Any]] = None

    # M13: 15-State SDLC lifecycle (the artifact's system of record).
    lifecycle_state: "SDLCState" = field(default=SDLCState.NEW)
    # G4 (Critical Incident Approval) grant — return edge IN_PRODUCTION → IN_PROGRESS.
    incident_approved: bool = False

    # Metadata
    run_id: Optional[str] = None
    started_at: Optional[float] = None
    completed_at: Optional[float] = None
