"""
create_story skill — create a User Story work item in Azure DevOps.

Live path:   POST to ADO Work Items API (User Story type); returns real ID + URL.
Offline path: Deterministic stub when ADO credentials are absent.
"""
from __future__ import annotations

import hashlib
import logging
import os
from typing import Any, Dict

logger = logging.getLogger(__name__)


async def create_story(request: str, ado_token: str = "") -> Dict[str, Any]:
    """
    Create a User Story work item in Azure DevOps.

    Args:
        request:   Plain-English feature description (becomes the story title).
        ado_token: ADO PAT injected by AgentContext (maps to AZURE_DEVOPS_TOKEN).

    Returns:
        {"story_id": int, "story_url": str, "title": str, "stub": bool}
    """
    title = _derive_title(request)
    description = f"<p>Auto-generated by Continuum.</p><p>{request}</p>"

    try:
        from integrations.azure_devops_mcp import AzureDevOpsClient  # type: ignore

        client = AzureDevOpsClient.from_env(token=ado_token)
        result = await client.create_work_item(
            work_item_type="User Story",
            title=title,
            description=description,
        )
        logger.info(
            "[create_story] work-item id=%s stub=%s", result["id"], result.get("stub")
        )
        return {
            "story_id":  result["id"],
            "story_url": result["url"],
            "title":     result["title"],
            "stub":      result.get("stub", False),
        }

    except Exception as exc:  # noqa: BLE001
        logger.warning("[create_story] ADO call failed (%s) — offline stub", exc)

    # Offline / fallback stub
    stub_id = int(hashlib.md5(request.encode()).hexdigest()[:8], 16)  # noqa: S324
    org  = os.getenv("AZURE_DEVOPS_ORG_URL") or os.getenv("AZURE_DEVOPS_ORG") or ""
    proj = os.getenv("AZURE_DEVOPS_PROJECT", "")
    url  = (
        f"{org.rstrip('/')}/{proj}/_workitems/edit/{stub_id}"
        if org and proj
        else f"https://dev.azure.com/stub/work-items/{stub_id}"
    )
    return {"story_id": stub_id, "story_url": url, "title": title, "stub": True}


def _derive_title(request: str) -> str:
    words = request.strip().split()
    return " ".join(words[:10]).rstrip(".,;") or "Feature"
